### ISSUE TITLE
Module name lint error

### ISSUE THREAD

**Issue by jwdonal** [bhoogter/VB6TocSharp#15]
I'm getting several of these errors that seems to have no resolution:

LINT FAILED: C:\Temp\_vb6_junk\modFileIO.bas
Module name [modFileIO.bas] must match file name [modFileIO.bas].  Rename module or class to match the other
?Lint("C:\Temp\_vb6_junk\modFileIO.bas")

It's saying the names must match but they already do match.    ......?

**Comment by bhoogter** [comment]
Sure.  So, after fixing two legitimate lint errors in the master branch just now, I then renamed the module `modVB6ToCS` to `modVB6ToCSx` and ran the linter against itself.  Notice the file is called `modVB6ToCS.bas`, which doesn't match the actual module name per the picture (see bottom).  This yields an error message of:

> `Module name [modVB6ToCSx] must match file name [modVB6ToCS.bas].  Rename module or class to match the other`

So, normally, you name the module the same as the filename, minus the file extension.  However, in your case, are you manually editing the project file?  I don't see the IDE allowing you to use the period (`.`) in the module name, so I'm not sure how yours is functioning this way.  Is it VB6 with Service Pack 6 installed?

Regardless, if the module name (not file name) does have the `.bas`, try without it.  If the module name is somehow being detected as having the `.bas`, let me know and I can keep digging.

![image](https://user-images.githubusercontent.com/11167440/167859427-7f0da27d-27fb-4ebd-a771-f5bb6f73ea3e.png)

**Comment by jwdonal** [comment]
Yes, you are correct sir. I was editing the name directly in the source file. I removed the extension and then linter stopped complaining.

To avoid this confusion might I suggest a slight change to the error message so that it doesn't include the file extension? Because saying "Module name [modFileIO.bas] must match file name [modFileIO.bas]" is super confusing - since they already do match.
