### ISSUE TITLE
No migration for WITH construct?

### ISSUE THREAD

**Issue by jwdonal** [bhoogter/VB6TocSharp#16]
myTestForm.frm [Migra] Line    22: Remove all uses of WITH.  No migration path exists.  Indent check disabled.

Why is there no migration path for WITH? It seems to me that in 99% of cases a migration of the WITH construct would be incredibly trivial.  For example, the following...

    With Me
        .Left = 1234
        .Top = 4567
        .Height = 4620
        .Width = 5775
    End With

...could be easily converted to...

Me.Left = 1234
Me.Top = 4567
Me.Height = 4620
Me.Width = 5775

I'm trying to understand how there is no migration path with such a simple construct?

**Comment by jwdonal** [comment]
You make excellent points. My thoughts are this:

- There is nothing at all wrong with only supporting refactoring of simple WITH statements and not complex ones. 99% (possibly 100%?) of all of my WITH statements are like my example above. That is:

With <frm_name>
    .Left = 1234
    .Top = 4567
    .Height = 4620
    .Width = 5775
End With

- If you encounter a complex WITH statement, simply inform the user "refactoring of complex WITH statements not supported" or the like.

- I had no idea you could nest WITH statements, nor did I know you could use it with function calls. Interesting stuff. I love VB6.

- My personal opinion is a simple non-nested, no-function-call WITH statement that only assigns to variables/parameters is a very commonly used case and very low hanging fruit that you could add to your refactoring. Even IF an intermediate variable was required - intermediate variables are not a big deal.

- "I don't think this would fully please anyone" - I have to disagree on only this one small point. It would please me just fine and dandy because the fact of the matter is that it prevented me from having to manually convert all 108 of the simple WITH statements in my code by hand. I see extreme value in it. But just my 2 cents.

- I'm willing to put my money where my mouth is. If you accept any kind of monetary donations let me know how much implementing refactoring of *simple* WITH statements is worth to you and I'd compensate you for your time.

Thanks!

**Comment by bhoogter** [comment]
This along with Issue #15 should be fixed by this PR.  Simply removed any extension for the other.  For this one, current operation for WITH would produce results similar to the following...  Comments may be a little spammy, but just trying to keep visibility post-convert.

 ```vba
Public Sub VerifyWith()
  With frm   ' Should be permitted.
    .Caption = .Caption
    .Top = 0
  End With
  
  With getFrm() ' Should NOT be permitted.
    .Caption = ""
    .Top = 0
  End With

  
  With frm ' Should be permitted.
    With .txtFile ' Should NOT be permitted
      .Text = ""
      .Top = 0
    End With
  End With
End Sub
```

Converts to:

```vba
    public static void VerifyWith()
    {
        // Converted WITH statement: With frm // Should be permitted.
        frm.instance.Title = frm.instance.Title;
        frm.instance.Top = 0;
        // With getFrm() // TODO (not supported): Expression used in WITH.  Verify result: getFrm()
        dynamic __withVar962 = getFrm(); ; // Should NOT be permitted.
        __withVar962.Caption = "";
        __withVar962.Top = 0;
        // Converted WITH statement: With frm // Should be permitted.
        // With .txtFile // TODO (not supported): Expression used in WITH.  Verify result: .txtFile
        dynamic __withVar432 = frm.instance.txtFile; ; // Should NOT be permitted
        __withVar432.Text = "";
        __withVar432.Top = 0;
    }
```
