### ISSUE TITLE
Line number handling?

### ISSUE THREAD

**Issue by t-johnson** [bhoogter/VB6TocSharp#18]
This tool looks super promising, and i threw our most horrible VB6 project at it just for fun.  surprisingly it didn't crash right away!

There does seem to be an issue with the parsing of VB6 code where there are line numbers.  eg:
```
Private Sub Something()
100     Dim Index As Integer
           MsgBox "Test"
End Sub
```

the generated code seems like it is assuming "100" is a function call:
100(Dim Index As Integer);

**Comment by t-johnson** [comment]
Suggested fix would be to add
`  
Line = RegExReplace(Line, "^[0-9]+", " ")
`
at the end of the CleanLine function in modQuickConvert

**Comment by bhoogter** [comment]
Good point.  VB6 has so many niche things, it's hard to remember all the ones you don't use regularly...

It seems like that would work well to simply remove them, but does your code have any places where it needs to then goto that line number?  It seems like inserting a C# label such as `Line100` would be more thorough.  Then, whenever one encounters a `GoTo ###` pattern, replace it with `Goto Line###`.

That seems like it would take care of anyone using `GoTo`, even if it makes spaghetti VB6 into linguini C#.  Would that work for your use case or any other you can think of?

**Comment by t-johnson** [comment]
For my use, simply ignoring the line numbers is the better choice. 
This old project has line numbers on almost every line of every function, and it's purpose seems to be in being able to indicate the exact line that errors occur on. That "functionality" is something we can live without as in a dotnet world that info is contained in the exception stack when thrown.

I also ran into cases where there were comments using "rem" ... a similar regex gets rid of those too.

**Comment by bhoogter** [comment]
How about a helper funciton called `REM(str)` which just no-op's.  J/K.  Both good points.  Will dig into these and get a patch soon (prob tomorrow some time).

**Comment by bhoogter** [comment]
Actually, this should handle both.  Went half way..  I parsed off the lineno, but didn't re-inject it into the C# code.  May revisit later and add an option in the config to omit them... or might just leave it until someone else asks, but it is certainly better than it was in both regards.
