### ISSUE TITLE
Cannot Compile VB6LIB.dll

### ISSUE THREAD

**Issue by MrHVAC** [bhoogter/VB6TocSharp#2]
Hello. Thank you for sharing this project. I am not able to compile the VB6Lib.dll file. When I open the vbSupportDLL.vbp project, I see the error message "Unable to set the version compatibility component." Below that message is the file path to the vb6lib.dll file. Of course, that file does not yet exist because I have not compiled it. If I click ok and try to compile, I get the message "No creatable public component detected." I appreciate any help you can offer. Thank you.

**Comment by bhoogter** [comment]
That was actually just left over from a previous iteration.  It is not part of the converter.

Please use the file:  **prj.vbp**

The other vbp file has been deleted.
