### ISSUE TITLE
Config fails, needs to begin with directory selection

### ISSUE THREAD

**Issue by LesF** [bhoogter/VB6TocSharp#3]
The Quick Start advice fails, if the directory set in the default variable does not exist.
A directory lookup would be a great way to start, if a valid path is not available.

**Comment by bhoogter** [comment]
Pushed commit to:

- Config Validator Function
- Require valid config on all button pushes
- Ensure no nag messages when attempting to enter config
- Ensure no error on startup
- Improve UX for single file

I believe this should fix your issue.

Also added ability to run GIT commands from the Immediate pane....
